# For more information: https://laravel.com/docs/sail
version: '3'
services:
  #    laravel.test:
  #        build:
  #            context: ./vendor/laravel/sail/runtimes/8.1
  #            dockerfile: Dockerfile
  #            args:
  #                WWWGROUP: '${WWWGROUP}'
  #        #image: sail-8.1/app
  #        image: kolekulyanov/sail-8.1 # password docker-kolek-ulyanov@yandex
  #        extra_hosts:
  #            - 'host.docker.internal:host-gateway'
  #        ports:
  #            - '${APP_PORT:-80}:80'
  #            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
  #        environment:
  #            WWWUSER: '${WWWUSER}'
  #            LARAVEL_SAIL: 1
  #            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
  #            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
  #        volumes:
  #            - '.:/var/www/html'
  #        networks:
  #            - sail
  #        depends_on:
  #            - mysql
  #    mysql:
  #        image: 'mysql/mysql-server:8.0'
  #        ports:
  #            - '${FORWARD_DB_PORT:-3306}:3306'
  #        environment:
  #            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
  #            MYSQL_ROOT_HOST: "%"
  #            MYSQL_DATABASE: '${DB_DATABASE}'
  #            MYSQL_USER: '${DB_USERNAME}'
  #            MYSQL_PASSWORD: '${DB_PASSWORD}'
  #            MYSQL_ALLOW_EMPTY_PASSWORD: 1
  #        volumes:
  #            - 'sail-mysql:/var/lib/mysql'
  #        networks:
  #            - sail
  #        healthcheck:
  #            test: [ "CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}" ]
  #            retries: 3
  #            timeout: 5s
  #    phpmyadmin:
  #        image: 'phpmyadmin'
  #        restart: always
  #        ports:
  #            - '8081:80'
  #        environment:
  #            - PMA_ARBITRARY=1
  #            - UPLOAD_LIMIT=300M
  #        networks:
  #            - sail
  #    runner-manager:
  #        build:
  #            context: .
  #        image: kolekulyanov/apache-docker
  #        environment:
  #            - APACHE_RUN_USER=#1000
  #        volumes:
  #            - ./runner_manager/app:/var/www/html
  #            - /var/run/docker.sock:/var/run/docker.sock
  #        ports:
  #            - ${RUNNER_MANAGER_PORT:-8082}:80
  apache-runner:
    restart: always
    #        build:
    #            context: ./runners/apache-runner/
    image: kolekulyanov/apache-runner # password docker-kolek-ulyanov@yandex
    environment:
      - APACHE_RUN_USER=#1000
    ports:
      - ${APACHE_RUNNER_PORT}:80
    volumes:
      - ./runners/apache-runner/app:/var/www/html
  laravel-runner:
    restart: always
    #        build:
    #            context: ./runners/laravel-runner/vendor/laravel/sail/runtimes/8.1
    #            dockerfile: Dockerfile
    #            args:
    #                WWWGROUP: '${WWWGROUP}'
    image: kolekulyanov/sail-runner:1.2 # password docker-kolek-ulyanov@yandex
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${LARAVEL_RUNNER_PORT:-81}:80'
    environment:
      WWWUSER: '${WWWUSER}'
      #XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
      #LARAVEL_SAIL: 1
    volumes:
      - './runners/laravel-runner:/var/www/html'
#    laravel-runner-min:
#        restart: always
#        build:
#            context: ./runners/laravel-runner-min/vendor/laravel/sail/runtimes/8.2
#            dockerfile: Dockerfile
#            args:
#                WWWGROUP: '${WWWGROUP}'
#        image: kolekulyanov/sail-runner-min:1.0 # password docker-kolek-ulyanov@yandex
#        extra_hosts:
#            - 'host.docker.internal:host-gateway'
#        ports:
#            - '${LARAVEL_RUNNER_MIN_PORT:-82}:80'
#        environment:
#            WWWUSER: '${WWWUSER}'
#            LARAVEL_SAIL: 1
#            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
#            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
#        volumes:
#            - './runners/laravel-runner-min:/var/www/html'
#networks:
#    sail:
#        driver: bridge
#volumes:
#    sail-mysql:
#        driver: local
